services:
  task1:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      - BED_FILE_PATH
      - GTF_FILE_PATH
      - INTERSECTED_PATH=intersected.bed
      - UNIPROT_INFO=uniprot_protein_data.xlsx
      - DEBUG = False
    command: ["bash"]