services:
  task1:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      - BED_FILE_PATH=IAD143293_241_Designed.bed
      - GTF_FILE_PATH=hg19.knownGene.gtf
      - INTERSECTED_PATH=intersected.bed
      - UNIPROT_INFO=uniprot_protein_data.xlsx
      - DEBUG = False
    command: ["bash"]